apiName: "IKPMD (Peters) API"

assets:
  mappings:
    /assets: /
  overrides:
    /: 

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
    driverClass: org.postgresql.Driver 
    user: postgres
    password: ennazuS94
    url: jdbc:postgresql://localhost:5432/ikpmd-politieApp
